//! The Claude Code plugin's tests check that its approval pane draws
//! every argument of every tool. They read the tools' argument names and
//! types from `claude-plugin/tests/tools.gen.ts`, written from the
//! router here: this test fails when that file is out of date.
//!
//! Regenerate: `PROMPTO_UPDATE_PLUGIN_SCHEMAS=1 cargo test --test plugin_schemas`.

use serde_json::{Map, Value, json};

/// `{ tool: { arg: type } }` with the JSON Schema type of each property
/// (`string`, `integer`, `boolean`, `array`, `object`; a nullable one by
/// its non-null type).
fn shapes() -> Map<String, Value> {
    let mut out = Map::new();
    for (tool, schema) in prompto::mcp::Prompto::tool_schemas() {
        let mut props = Map::new();
        if let Some(p) = schema.get("properties").and_then(Value::as_object) {
            for (name, prop) in p {
                props.insert(name.clone(), json!(kind(prop, &schema)));
            }
        }
        out.insert(tool, Value::Object(props));
    }
    out
}

fn kind(prop: &Value, root: &Value) -> String {
    if let Some(r) = prop.get("$ref").and_then(Value::as_str) {
        let path = r.trim_start_matches('#');
        if let Some(target) = root.pointer(path) {
            return kind(target, root);
        }
    }
    match prop.get("type") {
        Some(Value::String(t)) => t.clone(),
        Some(Value::Array(ts)) => ts
            .iter()
            .filter_map(Value::as_str)
            .find(|t| *t != "null")
            .unwrap_or("string")
            .to_string(),
        _ => ["anyOf", "oneOf", "allOf"]
            .iter()
            .filter_map(|k| prop.get(*k).and_then(Value::as_array))
            .flatten()
            .map(|p| kind(p, root))
            .find(|t| t != "null")
            .unwrap_or_else(|| "object".into()),
    }
}

fn render() -> String {
    let body = serde_json::to_string_pretty(&Value::Object(shapes())).unwrap();
    format!(
        "// Generated by tests/plugin_schemas.rs from prompto's tools/list: every\n\
         // tool's arguments and their JSON types. Don't edit; regenerate with\n\
         // PROMPTO_UPDATE_PLUGIN_SCHEMAS=1 cargo test --test plugin_schemas\n\n\
         export const TOOLS: Record<string, Record<string, string>> = {body}\n"
    )
}

#[test]
fn the_plugins_copy_of_the_tool_schemas_is_current() {
    let path =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("claude-plugin/tests/tools.gen.ts");
    let want = render();
    if std::env::var_os("PROMPTO_UPDATE_PLUGIN_SCHEMAS").is_some() {
        std::fs::write(&path, &want).unwrap();
        return;
    }
    let have = std::fs::read_to_string(&path).unwrap_or_default();
    assert!(
        have == want,
        "{} is out of date with tools/list: run PROMPTO_UPDATE_PLUGIN_SCHEMAS=1 cargo test --test plugin_schemas",
        path.display()
    );
}
