// Generated by tests/plugin_schemas.rs from prompto's tools/list: every
// tool's arguments and their JSON types. Don't edit; regenerate with
// PROMPTO_UPDATE_PLUGIN_SCHEMAS=1 cargo test --test plugin_schemas

export const TOOLS: Record<string, Record<string, string>> = {
  "bash_exec": {
    "host": "string",
    "script": "string",
    "args": "array",
    "timeout_secs": "integer"
  },
  "claude_exec": {
    "host": "string",
    "task": "string",
    "tier": "string",
    "backend": "string",
    "model": "string",
    "effort": "string",
    "session_id": "string",
    "timeout_secs": "integer"
  },
  "deno_exec": {
    "host": "string",
    "script": "string",
    "args": "array",
    "timeout_secs": "integer"
  },
  "file_list": {
    "host": "string",
    "path": "string"
  },
  "file_read": {
    "host": "string",
    "path": "string",
    "max_bytes": "integer"
  },
  "file_stat": {
    "host": "string",
    "path": "string"
  },
  "file_write": {
    "host": "string",
    "path": "string",
    "content": "string",
    "mode": "string",
    "sudo": "boolean"
  },
  "host_diagnose": {
    "host": "string"
  },
  "host_sleep": {
    "host": "string"
  },
  "host_status": {
    "host": "string"
  },
  "host_wake": {
    "host": "string"
  },
  "inventory_get_host": {
    "name": "string"
  },
  "inventory_list": {},
  "mcp_add": {
    "client": "string",
    "name": "string",
    "transport": "string",
    "url_or_cmd": "string",
    "scope": "string"
  },
  "mcp_get": {
    "client": "string",
    "name": "string"
  },
  "mcp_list": {
    "client": "string"
  },
  "mcp_logs": {
    "host": "string",
    "unit": "string",
    "lines": "integer"
  },
  "mcp_reconnect_hint": {},
  "mcp_remove": {
    "client": "string",
    "name": "string",
    "scope": "string"
  },
  "mcp_restart_claudecli": {
    "client": "string"
  },
  "mcp_status": {
    "client": "string"
  },
  "node_exec": {
    "host": "string",
    "script": "string",
    "args": "array",
    "timeout_secs": "integer"
  },
  "perl_exec": {
    "host": "string",
    "script": "string",
    "args": "array",
    "timeout_secs": "integer"
  },
  "port_scan": {
    "host": "string",
    "ports": "array",
    "probe_ms": "integer"
  },
  "prompto_gain": {
    "since_secs": "integer"
  },
  "python_exec": {
    "host": "string",
    "script": "string",
    "args": "array",
    "timeout_secs": "integer"
  },
  "rsync_sync": {
    "source_host": "string",
    "source_path": "string",
    "dest_host": "string",
    "dest_path": "string",
    "archive": "boolean",
    "delete": "boolean",
    "dry_run": "boolean",
    "excludes": "array",
    "dest_key": "string",
    "timeout_secs": "integer"
  },
  "ruby_exec": {
    "host": "string",
    "script": "string",
    "args": "array",
    "timeout_secs": "integer"
  },
  "service_control": {
    "host": "string",
    "unit": "string",
    "action": "string"
  },
  "service_logs": {
    "host": "string",
    "unit": "string",
    "lines": "integer"
  },
  "ssh_batch": {
    "host": "string",
    "commands": "array",
    "fail_fast": "boolean",
    "timeout_secs": "integer"
  },
  "ssh_exec": {
    "host": "string",
    "cmd": "string",
    "timeout_secs": "integer"
  },
  "ssh_sudo_exec": {
    "host": "string",
    "cmd": "string",
    "timeout_secs": "integer"
  },
  "vm_ensure_up": {
    "host": "string",
    "vm": "string",
    "total_timeout_secs": "integer"
  },
  "vm_list": {
    "host": "string"
  },
  "vm_start": {
    "host": "string",
    "vm": "string"
  },
  "vm_state": {
    "host": "string",
    "vm": "string"
  },
  "vm_stop": {
    "host": "string",
    "vm": "string",
    "step_timeout_secs": "integer"
  }
}
